### ISSUE TITLE
Cannot compile in Typescript 3.8

### ISSUE THREAD

**Issue by AragurDEV** [nikeee/node-ts#20]
I cannot compile my project.  
Compilation is failing with 30 errors:
```error TS2304: Cannot find name 'MapLike'.```

**Comment by nikeee** [comment]
A cannot reproduce this. The same goes [for the CI](https://travis-ci.com/github/nikeee/node-ts/jobs/309589201).

Could you provide more information on what you are doing?

**Comment by AragurDEV** [comment]
https://github.com/AragurDEV/Node-TS-Bug

Here you can see the error.  
Run npm install and npm run build

**Comment by nikeee** [comment]
I tried to fix this in 5.0.6. Let's see if it is still there.

**Comment by AragurDEV** [comment]
@nikeee It's working now, thanks a lot :)
